permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::035168537330:role/githubactions
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: us-east-1 
      - name: Terraform Init
        id: init
        working-directory: terraform
        run: terraform init 
      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -no-color
        continue-on-error: true
